package ogr.user12043.kanban12043.view;

import javax.swing.*;
import java.awt.*;

/**
 * Created by user12043 on 05.07.2018 - 14:11
 * Part of project: kanban12043
 */
public class KanbanContainer extends javax.swing.JPanel {

    private int last = 0;
    private boolean addVertical = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JPanel jPanel_content;
    private javax.swing.JScrollPane jScrollPane_content;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form KanbanContainer
     */
    public KanbanContainer() {
        initComponents();
        removeAll();
    }

    public KanbanContainer(String name) {
        setName(name);
        initComponents();
        removeAll();
    }

    public Component addKanban(Component comp) {
        GridBagConstraints c = new GridBagConstraints();
        c.gridy = last;
        c.gridx = 0;
        last++;
        c.fill = GridBagConstraints.BOTH;
        c.weightx = 1;
        c.insets = new Insets(0, 3, 10, 3);
//        c.weighty = 1;
        jPanel_content.add(comp, c);
        return comp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_name = new javax.swing.JLabel();
        jScrollPane_content = new javax.swing.JScrollPane();
        jPanel_content = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(0, 0));

        jLabel_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_name.setText(getName());
        jLabel_name.setToolTipText("");

        jScrollPane_content.setBorder(null);
        jScrollPane_content.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane_content.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel_content.setLayout(new java.awt.GridBagLayout());
        jScrollPane_content.setViewportView(jPanel_content);

        JScrollBar verticalScrollBar = new JScrollBar(JScrollBar.VERTICAL) {
            @Override
            public boolean isVisible() {
                return true;
            }
        };
        verticalScrollBar.setUnitIncrement(30);
        jScrollPane_content.setVerticalScrollBar(verticalScrollBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_name, javax.swing.GroupLayout.DEFAULT_SIZE, 4, Short.MAX_VALUE)
                        .addComponent(jScrollPane_content)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane_content))
        );
    }// </editor-fold>//GEN-END:initComponents
}
