/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ogr.user12043.kanban12043.view;

import java.awt.*;

/**
 * Created by user12043 on 05.07.2018 - 14:11
 * Part of project: kanban12043
 */
public class KanbanContainer extends javax.swing.JPanel {
    private int last = 0;

    private boolean addVertical = false;

    /**
     * Creates new form KanbanContainer
     */
    public KanbanContainer() {
        initComponents();
        removeAll();
    }

    public KanbanContainer(boolean addVertical) {
        initComponents();
        removeAll();
        this.addVertical = addVertical;
    }

    @Override
    public Component add(Component comp) {
        GridBagConstraints c = new GridBagConstraints();
        if (addVertical) {
            c.gridy = last;
            c.gridx = 0;
        } else {
            c.gridx = last;
            c.gridy = 0;
        }
        last++;
        c.fill = GridBagConstraints.BOTH;
        c.weightx = 1;
        c.insets = new Insets(0, 3, 10, 3);
//        c.weighty = 1;
        add(comp, c);
        return comp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton_test1 = new javax.swing.JButton();
        jButton_test2 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        setLayout(new java.awt.GridBagLayout());

        jButton_test1.setText("test1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jButton_test1, gridBagConstraints);

        jButton_test2.setText("test2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jButton_test2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_test1;
    private javax.swing.JButton jButton_test2;
    // End of variables declaration//GEN-END:variables
}
