package ogr.user12043.kanban12043.view;

/**
 * Created by user12043 on 19.07.2018 - 13:42
 * Part of project: kanban12043
 */
public class TimerPanel extends javax.swing.JPanel {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_longBreak;
    private javax.swing.JButton jButton_shortBreak;
    private javax.swing.JButton jButton_start;
    private javax.swing.JButton jButton_stop;
    private javax.swing.JLabel jLabel_minute;
    private javax.swing.JLabel jLabel_second;
    private javax.swing.JLabel jLabel_separate;

    /**
     * Creates new form TimerPanel
     */
    public TimerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_second = new javax.swing.JLabel();
        jLabel_minute = new javax.swing.JLabel();
        jLabel_separate = new javax.swing.JLabel();
        jButton_start = new javax.swing.JButton();
        jButton_shortBreak = new javax.swing.JButton();
        jButton_longBreak = new javax.swing.JButton();
        jButton_stop = new javax.swing.JButton();

        jLabel_second.setFont(jLabel_second.getFont().deriveFont(jLabel_second.getFont().getSize() + 25f));
        jLabel_second.setText("00");

        jLabel_minute.setFont(jLabel_minute.getFont().deriveFont(jLabel_minute.getFont().getSize() + 25f));
        jLabel_minute.setText("00");

        jLabel_separate.setFont(jLabel_separate.getFont().deriveFont(jLabel_separate.getFont().getSize() + 25f));
        jLabel_separate.setText(":");

        jButton_start.setText("Start");

        jButton_shortBreak.setText("Short Break");

        jButton_longBreak.setText("Long Break");

        jButton_stop.setText("Stop");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel_minute)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_separate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_second)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_start)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_shortBreak)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_longBreak)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_stop)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel_minute)
                                        .addComponent(jLabel_second)
                                        .addComponent(jLabel_separate)))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton_start)
                                        .addComponent(jButton_shortBreak)
                                        .addComponent(jButton_longBreak)
                                        .addComponent(jButton_stop))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // End of variables declaration//GEN-END:variables
}
