package ogr.user12043.kanban12043.view.settings;

import ogr.user12043.kanban12043.utils.Constants;
import ogr.user12043.kanban12043.utils.Properties;
import ogr.user12043.kanban12043.utils.Utils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Created by user12043 on 14.07.2018 - 17:06 Part of project: kanban12043
 */
public class AppSettings extends javax.swing.JPanel {

    private static final Logger LOGGER = LogManager.getLogger(AppSettings.class);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_apply;
    private javax.swing.JComboBox<String> jComboBox_theme;
    private javax.swing.JLabel jLabel_theme;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form AppSettings
     */
    public AppSettings() {
        initComponents();
        setName(Utils.getTag("options"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_theme = new javax.swing.JLabel();
        jComboBox_theme = new javax.swing.JComboBox<>();
        jButton_apply = new javax.swing.JButton();

        jLabel_theme.setText(Utils.getTag("settings.theme") + "\t:");

        jComboBox_theme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Nimbus", "Metal", "Darcula", "Seaglass", "WebLaF"}));
        jComboBox_theme.setSelectedIndex(Properties.theme);
        jComboBox_theme.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jComboBox_themeMouseWheelMoved(evt);
            }
        });

        jButton_apply.setText(Utils.getTag("options.saveChanges"));
        jButton_apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_applyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton_apply)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel_theme)
                                                .addGap(77, 77, 77)
                                                .addComponent(jComboBox_theme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel_theme)
                                        .addComponent(jComboBox_theme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                                .addComponent(jButton_apply)
                                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_themeMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jComboBox_themeMouseWheelMoved
        try {
            jComboBox_theme.setSelectedIndex(jComboBox_theme.getSelectedIndex() + evt.getWheelRotation());
        } catch (Exception ignored) {
        }
    }//GEN-LAST:event_jComboBox_themeMouseWheelMoved

    private void jButton_applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_applyActionPerformed
        int index = jComboBox_theme.getSelectedIndex();
        if (index >= 0 && index < Constants.themes.length) {
            Properties.updateProperty(Constants.args_themeArgumentName, index);
            Properties.theme = index;
        }
    }//GEN-LAST:event_jButton_applyActionPerformed
}
