package ogr.user12043.kanban12043.view.settings;

import ogr.user12043.kanban12043.utils.Utils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import javax.swing.table.DefaultTableModel;

/**
 * Created by user12043 on 10.07.2018 - 16:52
 * Part of project: kanban12043
 */
public class SettingsDialog extends javax.swing.JDialog {
    private static final Logger LOGGER = LogManager.getLogger(SettingsDialog.class);
    private DefaultTableModel tableModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane_settings;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form SettingsDialog
     */
    public SettingsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        buildContent();
        setTitle(Utils.getTag("toolbar.settings"));
    }

    private void buildContent() {
        try {
            jTabbedPane_settings.add(new AppSettings());
            jTabbedPane_settings.add(new KanbanColumnSettings());
            jTabbedPane_settings.add(new TagSettings());
            jTabbedPane_settings.add(new TopicSettings());
            jTabbedPane_settings.add(new TaskViewSettings());
        } catch (Exception e) {
            LOGGER.error("An error occurred on build settings", e);
        }
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane_settings = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(Utils.getImage("settings.png", getClass()));
        setLocationByPlatform(true);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane_settings, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane_settings, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
}
