package ogr.user12043.kanban12043.view.settings;

import ogr.user12043.kanban12043.Main;
import ogr.user12043.kanban12043.dao.DaoUtil;
import ogr.user12043.kanban12043.dao.TaskDao;
import ogr.user12043.kanban12043.dao.TopicDao;
import ogr.user12043.kanban12043.model.Task;
import ogr.user12043.kanban12043.model.Topic;
import ogr.user12043.kanban12043.utils.Utils;
import ogr.user12043.kanban12043.view.settings.partial.TopicView;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.data.domain.Sort;

import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by user12043 on 11.07.2018 - 17:20
 * Part of project: kanban12043
 */
public class TopicSettings extends javax.swing.JPanel {
    private static final Logger LOGGER = LogManager.getLogger(TopicSettings.class);
    private final TopicDao topicDao = DaoUtil.getTopicDao();
    private List<Topic> topics = new ArrayList<>();
    private TaskDao taskDao = DaoUtil.getTaskDao();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ogr.user12043.kanban12043.view.settings.partial.RootPanel rootPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form TopicSettings
     */
    public TopicSettings() {
        initComponents();
        setName(Utils.getTag("entity.topics"));
        refreshTable();
        addActions();
    }

    private void addActions() {
        // Button actions
        rootPanel.addAddListener(this::add);
        rootPanel.addEditListener(this::edit);
        /*rootPanel.addDeleteListener(e -> {
            delete(e);
        });*/
        rootPanel.addDeleteListener(this::delete);
    }

    private void refreshTable() {
        topics = topicDao.findAll(Sort.by("id").ascending());
        DefaultTableModel tableModel = Utils.generateTableModelFromList(topics, Topic.class, false);
        rootPanel.setTableModel(tableModel);
    }

    private void add(ActionEvent evt) {
        TopicView view = new TopicView(Main.mainPane, true);
        view.setTitle(Utils.getTag("options.add"));
        view.setVisible(true);
        refreshTable();
    }

    private void edit(ActionEvent e) {
        final int index = rootPanel.getTable().getSelectedRow();
        if (index == -1) {
            Utils.errorDialog(this, Utils.getTag("messages.error.notSelected"));
            return;
        }
        TopicView view = new TopicView(Main.mainPane, true);
        view.setTitle(Utils.getTag("options.edit"));
        view.setTopic(topics.get(index));
        view.setVisible(true);
        refreshTable();
    }

    private void delete(ActionEvent e) {
        final int index = rootPanel.getTable().getSelectedRow();
        if (index == -1) {
            Utils.errorDialog(this, Utils.getTag("messages.error.notSelected"));
            return;
        }
        if (Utils.confirmDialog(this)) {
            Topic topic = topics.get(index);

            // First delete the topic from associated tasks
            for (Task task : topic.getTasks()) {
                task.setTopic(null);
                taskDao.save(task);
            }
            topicDao.delete(topic);
            refreshTable();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new ogr.user12043.kanban12043.view.settings.partial.RootPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(rootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(rootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
}
