package ogr.user12043.kanban12043.view.viewUtil;

import javax.swing.table.DefaultTableModel;
import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.List;
import java.util.Vector;

/**
 * Created by user12043 on 11.07.2018 - 11:20
 * Part of project: kanban12043
 */
public class CrudView extends javax.swing.JPanel {
    private Class<?> clazz;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JScrollPane jScrollPane_table;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form CrudView
     */
    public CrudView(Class<?> clazz, List<?> dataList) throws IllegalAccessException, NoSuchMethodException, InvocationTargetException, ClassNotFoundException {
        this.clazz = clazz;
        initComponents();
        initTable(dataList);
    }

    private void initTable(List<?> dataList) throws IllegalAccessException, NoSuchMethodException, InvocationTargetException, ClassNotFoundException {
        Field[] fields = clazz.getDeclaredFields();
        DefaultTableModel tableModel = new DefaultTableModel();
        // Create columns
        for (Field field : fields) {
            String name;
            DisplayField annotation = field.getAnnotation(DisplayField.class);
            if (annotation != null) {
                final String key = annotation.keyParam();
                final String methodDesc = annotation.method();
                if (!methodDesc.isEmpty()) {
                    // Resolve and invoke method
                    final int index = methodDesc.lastIndexOf('.');
                    final String methodName = methodDesc.substring(index + 1);
                    final String className = methodDesc.substring(0, index);
                    final Class<?> methodClass = Class.forName(className);
                    // If key exists, pass as argument to method
                    if (!key.isEmpty()) {
                        final Method method = methodClass.getDeclaredMethod(methodName, String.class);
                        name = method.invoke(methodClass, key).toString();
                    } else {
                        final Method method = methodClass.getDeclaredMethod(methodName);
                        name = method.invoke(methodClass).toString();
                    }
                } else {
                    name = annotation.value();
                }
            } else {
                name = field.getName();
            }
            tableModel.addColumn(name);
        }

        for (Object o : dataList) {
            Vector<Object> vector = new Vector<>();
            for (Field field : fields) {
                field.setAccessible(true);
                Object value = field.get(o);
                vector.add(value);
            }
            tableModel.addRow(vector);
        }

        jTable.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane_table = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButton_add = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();

        jTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane_table.setViewportView(jTable);

        jButton_add.setText("Add");

        jButton_delete.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane_table, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton_add)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton_delete)))
                                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane_table, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton_add)
                                        .addComponent(jButton_delete))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
}
